- name: create ec2 server and r53
  connection: local
  hosts: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
    packages:
    - boto3
    - botocore
    subnet_id: subnet-0859f74fcf0e0bed3
    instance_type: t3.micro
    sg_group: sg-00450fb4c83b6b01d
    image_id: ami-0220d79f3f480ecf5
  tasks:
  - name: Install AWS Python libraries
    ansible.builtin.pip:
      name: "{{item}}"
      executable: pip3.9
    loop: "{{ packages }}"
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ sg_group }}"
      image_id: "{{ image_id }}"
    loop: "{{ instances }}"
    register: ec2_info
  - name: print ec2_info
    tags: asdf
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"
